package com.pion.phonecleaner.data.junk

import com.pion.phonecleaner.domain.model.junk.AppRule
import com.pion.phonecleaner.domain.model.junk.JunkContentType
import com.pion.phonecleaner.domain.model.junk.SystemCacheRule
import com.pion.phonecleaner.domain.repository.JunkRuleCatalog
import kotlinx.collections.immutable.ImmutableList
import kotlinx.collections.immutable.persistentListOf

/**
 * The catalogue that ships. **Branch B of PENDING OWNER DECISION (1), settled 2026-09-06: our own
 * list, returned from code.** Branch A — porting the competitor's 41 system-cache rules and its
 * 208-app table out of the decompiled APK — was rejected, because the provenance of that rule set is
 * itself UNKNOWN (`r1-01` OQ4) and copying it carries the redistribution question the owner deferred
 * for a week. **No rule data from `decompiler/` is carried in this repository, and none may be added.**
 *
 * The consequence, stated rather than hidden: our totals will not match the competitor's. Twenty-one
 * of its 41 rules name Chinese game and advertising SDKs last shipped around 2013
 * (`UnityAdsVideoCache`, `MBSTGO`, `burstlyImageCache`, `.camelgames`, `dianxin`), which is dead
 * weight on a 2026 device; the handful that still fire there are the platform conventions below,
 * which are Android's, not anyone's intellectual property.
 *
 * ## The two admission rules for this file
 *
 * 1. **A path earns its place by being disposable, not by being large.** Everything here is either
 *    regenerated on demand by the platform (thumbnail caches) or written as scratch (the `temp` and
 *    `cache` conventions). Nothing here is a place a user puts a file.
 * 2. **A rule states why it is junk, or it does not go in.** A row a reviewer cannot justify is a row
 *    that eventually deletes someone's photographs.
 *
 * ## What this catalogue deliberately cannot express
 *
 * `Android/data/<pkg>/cache` — where a modern app's cache actually lives, and the single biggest
 * bucket on any real device — is **unreachable**, on every API level from 30 up, even holding
 * `MANAGE_EXTERNAL_STORAGE` (`gioi-han-android-phone-cleaner` §1). There is no rule for it here
 * because there is no way to size it and no way to delete it. The app-residual table
 * ([JunkAppResidualRules]) says the same thing structurally, with `AppRuleRoot.scoped`.
 *
 * DECLARED IN `junkDataModule`. Replacing it is one line there, which is the whole point of
 * [JunkRuleCatalog] being an interface.
 */
internal class KotlinJunkRuleCatalog : JunkRuleCatalog {

    override suspend fun systemCacheRules(): ImmutableList<SystemCacheRule> = SYSTEM_CACHE_RULES

    override suspend fun appRules(): ImmutableList<AppRule> = JunkAppResidualRules.RULES
}

/**
 * Thumbnail caches, then scratch directories, then one filesystem artefact. Paths are relative to a
 * storage root — `RuleJunkScanner` resolves each against every readable volume, so a removable card
 * is covered by the same twelve rules as internal storage. The competitor resolves against one
 * statically cached root and never sees an SD card at all (`java/xc/z.java:20-29`).
 *
 * **The thumbnail rules are the ones that actually fire.** `.thumbnails` under a media directory is
 * the media scanner's own cache: it is rebuilt on demand, it is invisible to the gallery, and on a
 * photo-heavy device it is routinely the largest disposable directory in public storage. That is
 * where the bulk of a realistic "system junk" figure comes from.
 *
 * **The five scratch rules are conventions, not guarantees.** `cache`, `temp` and their dotted forms
 * at a volume root are what a decade of apps have used for working files; they are not defined by
 * AOSP and a user could in principle have made a folder called `temp` by hand. That is survivable
 * here and nowhere else in the app, because every row this pass produces is rendered on the review
 * screen with its path and its size and is unticked with one tap before anything is deleted
 * (`docs/screens/12-junk-cleaning.md` §4). A pass that deleted without that screen could not carry
 * these five.
 */
private val SYSTEM_CACHE_RULES: ImmutableList<SystemCacheRule> = persistentListOf(
    // Regenerated by the media scanner. Six locations, because the scanner writes one cache per
    // media directory and a device populates whichever of them its camera and downloads use.
    SystemCacheRule("thumbnails-root", ".thumbnails", JunkContentType.Thumbnails),
    SystemCacheRule("thumbnails-dcim", "DCIM/.thumbnails", JunkContentType.Thumbnails),
    SystemCacheRule("thumbnails-pictures", "Pictures/.thumbnails", JunkContentType.Thumbnails),
    SystemCacheRule("thumbnails-movies", "Movies/.thumbnails", JunkContentType.Thumbnails),
    SystemCacheRule("thumbnails-music", "Music/.thumbnails", JunkContentType.Thumbnails),
    SystemCacheRule("thumbnails-download", "Download/.thumbnails", JunkContentType.Thumbnails),

    // Scratch conventions. See the KDoc above for why these are admissible only because the review
    // screen stands between this list and the deleter.
    SystemCacheRule("scratch-cache", "cache", JunkContentType.Cache),
    SystemCacheRule("scratch-cache-hidden", ".cache", JunkContentType.Cache),
    SystemCacheRule("scratch-temp", "temp", JunkContentType.Cache),
    SystemCacheRule("scratch-temp-hidden", ".temp", JunkContentType.Cache),
    SystemCacheRule("scratch-tmp", "tmp", JunkContentType.Cache),

    // Fragments the platform recovers into after an unclean unmount of a FAT volume. They are
    // orphaned chunks with no directory entry — never a file the user can open again.
    SystemCacheRule("recovery-lost-dir", "LOST.DIR", JunkContentType.Unknown),
)
