package com.pion.phonecleaner.data.applock

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Wraps and unwraps the PIN salt with an Android Keystore AES key.
 *
 * `docs/screens/16-app-lock.md` §2.5: *"the digest and the salt go in DataStore, the salt wrapped by
 * an Android Keystore AES key so a file-level copy is not enough"*. This class is that sentence.
 *
 * ### Why the salt and not the digest
 *
 * Wrapping the digest would make the digest unreadable without the key — and so would wrapping the
 * salt, because the digest is useless without it. The salt is the smaller, fixed-size secret, and
 * wrapping it keeps the verify path to one Keystore round trip rather than one per stored field.
 *
 * ### What it actually buys, stated plainly
 *
 * A four-digit PIN is a 10 000-entry space. An attacker who has the DataStore file **and** the
 * Keystore key can exhaust it whatever the KDF cost. What this closes is the case that matters in
 * practice and that the competitor leaves wide open: a copy of the app's data directory — a backup,
 * an `adb` pull on a rooted device, another process that can read the file — is not enough, because
 * the key never leaves the Keystore and is non-exportable by construction.
 *
 * The key is created on first use and is **not** user-authentication-bound: requiring device
 * authentication to check an App Lock PIN would make the PIN pointless.
 */
internal class KeystoreSaltVault(
    private val keyAlias: String = DEFAULT_ALIAS,
) {

    /** Base64 of `iv || ciphertext`. One string, so one preference key holds it. */
    fun wrap(salt: ByteArray): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val ciphertext = cipher.doFinal(salt)
        return Base64.encodeToString(cipher.iv + ciphertext, Base64.NO_WRAP)
    }

    /**
     * Reverses [wrap].
     *
     * Throws when the blob is malformed or the key is gone — a factory reset, a restore onto another
     * device, or a user who cleared the Keystore. The caller turns that into a failed verification
     * rather than a crash, and the recovery is "Clear App Lock" (`docs/screens/16-app-lock.md`
     * §4.2), which is the only honest one once the PIN is irreversibly hashed.
     */
    fun unwrap(wrapped: String): ByteArray {
        val blob = Base64.decode(wrapped, Base64.NO_WRAP)
        require(blob.size > IV_BYTES) { "wrapped salt is too short to contain an IV" }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            secretKey(),
            GCMParameterSpec(TAG_BITS, blob, 0, IV_BYTES),
        )
        return cipher.doFinal(blob, IV_BYTES, blob.size - IV_BYTES)
    }

    private fun secretKey(): SecretKey {
        val store = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (store.getEntry(keyAlias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        return generateKey()
    }

    private fun generateKey(): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                keyAlias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_BITS)
                // A fresh IV per wrap, generated by the provider. Reusing one under GCM with the
                // same key destroys the mode's guarantees outright.
                .setRandomizedEncryptionRequired(true)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val DEFAULT_ALIAS = "phone_cleaner_app_lock_salt"
        const val KEY_BITS = 256
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}
